const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
short count = 0;
bool Iso = false;
bool on  = false;
bool red = false;
bool Program = false;
bool color = false;
int programselect = 0;
 short Isolation_RED_Program = 0;
 short Interaction_RED_Program = 0;
 short Isolation_BLUE_Program = 0;
 short Interaction_BLUE_Program = 0;
 ////////////////////////////////////////////////////////////////////////////
 int brightest = 1024;
int i = 0;
int lineaverage;
int lasttask;
bool junction = false;
const int left = 0;
const int right = 1;
const int centre = 2;
const bool front = true;
const bool back = false;
