#pragma config(Sensor, in1,    armpot,              sensorPotentiometer)
#pragma config(Sensor, dgtl1,  ncoder1,             sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




task main()
{
 #include "void func.c" //Funtion Library

  {
    SensorValue[ncoder1] = 0;
    movestraigh(800);

  }
}
