#pragma config(Sensor, in2,    Tubecounter,         sensorReflection)
#pragma config(Sensor, dgtl1,  Encoder,             sensorQuadEncoder)
#pragma config(Motor,  port6,           awe,           tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int color = 250; // take real values later...
int many = 6;//max tube.
char shooter = motor[awe];
char counter = SensorValue[Tubecounter];


void collect()
{
  if(counter < color)
  {
    shooter = 127;
  }
  else
    shooter = 0;
}
void shootout(int tubes, short timeout)

{
  ClearTimer(T4);
  SensorValue[Encoder] = 0;
  while(time1[T4] < timeout * 1000)//seconds
  {
    for (int i = 0; i < many; i++)
    {
      if (counter >= color)//if the the sensor sees a tube
      {
        if(SensorValue[Encoder] < 100)// the motors shoots it out
        {
          shooter = 127;
        }

        else
          i = many;// stop motors...


      }

    }

  }

  shooter = 0;

}

task main()
{
  collect();
  shootout(5,3);
}
