#pragma config(Sensor, in1,    armpot,              sensorPotentiometer)
#pragma config(Sensor, dgtl1,  ncoder1,             sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void movestraigh( int encodercount)
{
  SensorValue[ncoder1] = 0;
  while(SensorValue[ncoder1] < encodercount)
  { motor[port2] = 127;
    motor[port3] = 127;
    motor[port4] = 127;
    motor[port5] = 127;
    motor[port6] = 127;
    motor[port7] = 127;
 }
}
void turnleft(int encodercount)
{
  SensorValue[ncoder1] = 0;
  while(SensorValue[ncoder1] > encodercount)
  {
    motor[port2] = -127;
  }
}

void liftarm(int armcount)
{
  while(SensorValue[armpot] < armcount)
  {
    motor[port2] = 127;
  }
}
















task main()
{
  {

    movestraigh(800);
  }


{
    turnleft(-100);
  }



}
