#pragma config(UART_Usage, UART1, VEX_2x16_LCD)
#pragma config(Sensor, in1,    GyroInput,           sensorGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*        Module:     GyroExample.c                                            */
/*        Author:     jpearman                                                 */
/*        Created:    25 July 2011                                             */
/*                                                                             */
/*        Revisions:  V0.1                                                     */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*        Description:                                                         */
/*                                                                             */
/*        Example for the use the VEX Gyro                                     */
/*                                                                             */
/*        RobotC V2.32 does not work correctly with the new VEX gyro out of    */
/*        the box.  There seem to be two issues.                               */
/*        Scaling is wrong, turning the gyro results in a change of 450 in     */
/*        the sensor value (45 deg). Changing SensorScale to 130 helps with    */
/*        this.                                                                */
/*        There is some type of zero crossing issue.  The first rotation in    */
/*        either direction has an incorrect rollover from 0 to 359 deg.        */
/*        The following code is a tempory fix until CMU releases an update     */
/*        to RobotC.                                                           */
/*                                                                             */
/*        This code works on my system, it may behave differently on yours due */
/*        to differences in the sensor, cabling or other rf interference.      */
/*                                                                             */
/*        This code is an alternatove to reading the raw data from the gyro    */
/*        and integrating that data into angular data.                         */
/*                                                                             */
/*        Gyro is connected to Analog port 1                                   */
/*        LCD for debugging is connected to UART1                              */
/*                                                                             */
/*-----------------------------------------------------------------------------*/
/*                                                                             */

bool  gyro_valid = false;
float gyro_angle;

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*      Task to dump current angle on the LCD                                  */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

task display_task()
{
    string  str;

    // I like the backlight on
    bLCDBacklight = true;

    // loop forever
    while(1)
        {
        // display on line 1
        displayLCDPos(1, 0);

        // Is the data valid ?
        if( gyro_valid )
            {
            // display current value
            sprintf(str,"Gyro %5.1f   ", gyro_angle);
            displayNextLCDString( str );
            }
        else
            {
            displayNextLCDString( "Init Gyro.." );
            }

        // no need to update that fast
        wait1Msec( 20 );
        }
}

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  Task to init the Gyro and update the global variable gyro_angle every 20mS */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

task GetGyro()
{
    int     realBias;
    int     value;
    float   angle;
    float   offsetAngle;

    // Cause the gyro to reinitialize (a theory anyway)
    SensorType[GyroInput] = sensorNone;

    // Wait 1/2 sec
    wait10Msec(50);

    // Gyro should be motionless here
    SensorType[GyroInput] = sensorGyro;

    // Wait 1/2 sec
    wait10Msec(50);

    // Make a note of the bias found
    realBias = SensorBias[GyroInput];

    // Change the bias to a smaller value
    // The typical bias for the VEX gyro is 1874 so set to perhaps 1000 less
    // What this will do is fool the RobotC firmware into thinking the
    // Gyro is turning at a fast rate.  This gets us away from the condition where
    // the first revolution has an incorrect rollover from 3599 to 0 ie. it rolls over at some
    // smaller number, for example, I see rollover from 2304 to 0
    SensorBias[GyroInput] = SensorBias[GyroInput] - 1000;

    // Wait 1 second, gyro thinks we are rotating
    // May need to wait longer or set bias lower but this
    // will do for the demo.
    wait10Msec(100);

    // Now put the bias back to the correct value we found in the initialization
    SensorBias[GyroInput] = realBias;

    // Change sensor scale, the default is 260 but gives incorrect angles
    // the value of 130 was found by trial and error (more or less)
    // This number may need trimming slightly
    SensorScale[GyroInput] = 130;

    // We have an offset so note the current value so we can re-zero.
    offsetAngle =  SensorValue[GyroInput];

    // loop forever
    while(true)
        {
        // get current gyro value (deg * 10)
        value = SensorValue[GyroInput];

        // Create float angle, remove offset
        angle = (value - offsetAngle) / 10.0;

        // normalize into the range 0 - 360
        if( angle < 0 )
            angle += 360;

        // put in global for display
        gyro_angle = angle;

        // We can use the angle
        gyro_valid = true;

        // Delay
        wait1Msec( 20 );
        }
}

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  Start tasks and wait forever                                               */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

task main()
{
    StartTask( GetGyro );
    StartTask( display_task );

    while(1)
        {
        // do nothing
        wait10Msec( 100 );
        }
}
