#pragma config(Sensor, in1,    Line1,               sensorLineFollower)
#pragma config(Sensor, in2,    Line2,               sensorLineFollower)
#pragma config(Sensor, in3,    Line3,               sensorLineFollower)
#pragma config(Sensor, dgtl1,  Touch,               sensorTouch)
#pragma config(Sensor, dgtl2,  ncoderarm,           sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int programselect = 1;
bool redteam = true;
bool programselecting = true;
const int totalprogramnumber = 5;
//function:
void screenrefresh()
{
  clearLCDLine(1);
  displayLCDPos(1,0);
  if (redteam == true)
  {
    displayNextLCDString("RED ");
  }
  if (redteam == false)
  {
    displayNextLCDString("BlUE");
  }
  displayNextLCDString("    ");
  displayNextLCDNumber(programselect);
  displayNextLCDString("     OK");
}
void cls(){
SensorValue(ncoderarm) = 0;
}

void arm(int speed, int ticks){
 cls();
     while(SensorValue[Touch] ==1 && SensorValue[ncoderarm] <= ticks);
    {
      motor[port5] = speed;
      motor[port6] = speed;
      motor[port7] = speed;
      motor[port8] = speed;
    }
  }

  void LCD(){
    {

    clearLCDLine(0);
    clearLCDLine(1);                                      // Clear LCD Bottom Line
    displayLCDPos(1,0);                                   // Set the cursor to bottom line, first position
    displayNextLCDString("Arm: ");                   // Print "Potentio: " starting at the cursor position
    displayNextLCDNumber(SensorValue(ncoderarm));    // Display the reading of the Potentiometer to current cursor position
    displayLCDPos(0,5);
    displayNextLCDString("Touch: ");
    displayNextLCDNumber(SensorValue(Touch));

    }
  }
