#pragma config(Motor,  port6,           port6,         tmotorNormal, openLoop)
#pragma config(Motor,  port7,           port7,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           port8,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port9,           port9,         tmotorNormal, openLoop)
#pragma config(Motor,  port10,          Claw,          tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (true)
	{
	  	if(vexRT[Ch2] < 15 && vexRT[Ch2]> -15 )
                {
                     motor[port2] = 0;
                     motor[port3] = 0;
                     motor[port4] = 0;
                     motor[port5] = 0;                //...drive train motors = 0
                } //: if
                else
                {


    motor[port2]  = (vexRT[Ch2]  -vexRT[Ch1]);  // (y + x)/2
    motor[port3]  = (vexRT[Ch2] +vexRT[Ch1]);a

                }//: else

                 	switch(vexRT[Btn5D] - vexRT[Btn5U])
                	{
                    	case  1:motor[Claw] = -127; //Close
                            	break;
                    	case -1:motor[Claw] = 127; //Open
                            	break;
                    	case  0:motor[Claw] = 0; //Do nothing
                            	break;
      	}
      		  	if(vexRT[Ch3] < 15 && vexRT[Ch3]> -15)
                {
                     motor[port6] = 0;
                     motor[port7] = 0;
                     motor[port8] = 0;
                     motor[port9] = 0;                //...drive train motors = 0
                } //: if
                else
                {


    motor[port6]  = (vexRT[Ch2]  -vexRT[Ch1]);  // (y + x)/2
    motor[port7]  = (vexRT[Ch2]  -vexRT[Ch1]);
    motor[port8] = (vexRT[Ch2] - vexRT[Ch1]);  // (y - x)/2
    motor[port9] = (vexRT[Ch2] - vexRT[Ch1]);


      }

 } //while
      	/*switch(vexRT[Btn6U] - vexRT[Btn6D]) //manual arm control
        	{
            	case  1:motor[port6] = -127;
            	motor[port7] = -127;
            	motor[port8] = -127;
            	motor[port9] = -127;

                //unlocks arm
              break;

              /*case -1:motor[port6] = 127;
            	motor[port7] = 127;
            	motor[port8] = 127;
            	motor[port9] = 127;
              //unlocks arm
             	break;

             	case  0: {
              motor[port6] = 0;
            	motor[port7] = 0;
            	motor[port8] = 0;
            	motor[port9] = 0;
            	break;
         	    }//switch
  	      }

              }//while
          }//task main*/
        }//task main
