#pragma config(Sensor, in1,    detectBall,          sensorReflection)
#pragma config(Sensor, in2,    gyro,                sensorGyro)
#pragma config(Sensor, dgtl1,  btnLiftUpL,          sensorTouch)
#pragma config(Sensor, dgtl2,  btnLiftUpR,          sensorTouch)
#pragma config(Sensor, dgtl3,  btnLiftDownL,        sensorTouch)
#pragma config(Sensor, dgtl4,  btnLiftDownR,        sensorTouch)
#pragma config(Sensor, dgtl5,  btnBackL,            sensorTouch)
#pragma config(Sensor, dgtl6,  btnBackR,            sensorTouch)
#pragma config(Sensor, dgtl7,  btnFrontL,           sensorTouch)
#pragma config(Sensor, dgtl8,  btnFrontR,           sensorTouch)
#pragma config(Sensor, dgtl9,  encL,                sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encR,                sensorQuadEncoder)
#pragma config(Motor,  port2,           rightFront,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           rightMiddle,   tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           rightBack,     tmotorNormal, openLoop)
#pragma config(Motor,  port8,           suckR,         tmotorNormal, openLoop)
#pragma config(Motor,  port9,           suckL,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port1,           liftR,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port10,           liftL,         tmotorNormal, openLoop)
#pragma config(Motor,  port7,          leftBack,      tmotorNormal, openLoop)
#pragma config(Motor,  port6,          leftMiddle,    tmotorNormal, openLoop)
#pragma config(Motor,  port5,          leftFront,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

/*INCLUDES*/
#include "Vex_Competition_Includes.c"
#include "zeta_lib 2.c"

/*PRE AUTONOMOUS*//////////////////////////////////////////////////////////////
void pre_auton() {}

/*AUTONOMOUS*//////////////////////////////////////////////////////////////////
task autonomous() {
  //drive backwards to low goal
  drive_msec(-FULL, 900);
  //score preload
  suck_msec(-FULL, 4500);
  //return home
  /*drive_forward_msec(FULL, 600);

  /////////Insert button control here//////////////
  ///User loads 4 and lines up with middle tower///

  //drive to tower
  drive_to_tower(FULL, -1);
  //raise lift
  lift_up(FULL);
  //spit out/score
  suck_msec(-FULL,900);
  //lower lift
  lift_down(FULL);
  //Drive home
  drive_forward_msec(FULL, 2000);*/
}//Auton

/*TELE OP*//////////////////////////////////////////////////////////////////////
task usercontrol() {

  //Arcade functions: Enable this when enabling arcade
  /*int joy_x;            // will hold the X value of the analog stick (choices below)
  int joy_y;            // will hold the Y value of the analog stick (choices below)
  int threshold = 10;   // helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)
  */
  //

  while (true) {

    // drive
    //tank
tankDrive();
//arcadeDrive();


    //suck
    suck();
    //setRotateSpeed((vexRT[Btn8L] - vexRT[Btn8R])*FULL);
    //setSuckSpeed((vexRT[Btn6U] - vexRT[Btn6D])*FULL);

    //raise lift
    lift();

    /////Auto Controls


    //auto raise suck
    if ((vexRT[Btn8U]) == 1) {
      if (SensorValue[detectBall] < 200) {
        setSuckSpeed(FULL);
      }
      else {
        killSuck();
      }


      //auto raise lift
      if ((vexRT[Btn7U]) == 1) {
        lift_btn(FULL, 1);
      }
      /*if ((vexRT[Btn7L]) == 1) {
      if (SensorValue[btnLiftUpL] == 0) {
      setLiftSpeed(FULL);
      }
      else {
      killLift();
      }
      }
      */

      //auto lower lift
      if ((vexRT[Btn7D]) == 1) {
        lift_btn(FULL, -1);
      }
      /*if ((vexRT[Btn7R]) == 1) {
      if (SensorValue[btnLiftDownL] == 0) {
      setLiftSpeed(FULL);
      }
      else {
      killLift();
      }
      }*/

    }//WHILE
  }//TELEOP

}/*END*/
