#pragma config(UART_Usage, UART2, VEX_2x16_LCD)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
//Wait for Press--------------------------------------------------


const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
short count = 0;
bool Iso = false;
bool on  = false;
bool red = false;
bool Program = false;
bool preauton = false;
bool color = false;
int programselect = 0;

void waitForPress()
{
  while(nLCDButtons == 0);
  {
    wait1Msec(5);
  }
}
//----------------------------------------------------------------

//Wait for Release------------------------------------------------
void waitForRelease()
{
  while(nLCDButtons != 0);
  {
    wait1Msec(5);
  }
}
//----------------------------------------------------------------

//Function to increment and decriment count - small savings on space
void menuTracker()
{
  if(nLCDButtons == leftButton)
  {
    waitForRelease();
    count--;
  }
  else if(nLCDButtons == rightButton)
  {
    waitForRelease();
    count++;
  }
}

void clearLCD()
{
  clearLCDLine(1);
  clearLCDLine(2);

}
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{



  clearLCDLine(0);
  clearLCDLine(1);//clean up
  waitForRelease();

  while (on == false)
  {


      bLCDBacklight = true;
      switch (count){
      case 0:
        displayLCDCenteredString(0, "Isolation");
        displayLCDCenteredString(1, "<    Enter     >");
        waitForPress();
        if(nLCDButtons == centerButton)
        {
          clearLCD();
          on = true;
          waitForRelease();
          Iso = true;

          displayLCDCenteredString(0, "Isolation Zone");
          displayLCDCenteredString(1, "  Selected      ");
          wait1Msec(2000);
        }

        else if(nLCDButtons == leftButton)
        {
          waitForRelease();
          count = 1;
        }

        else if(nLCDButtons == rightButton)
        {
          waitForRelease();
          count++;
        }
        break;



      case 1:
        displayLCDCenteredString(0, "Interaction Zone");
        displayLCDCenteredString(1, "<    Enter     >");
        waitForPress();
        if(nLCDButtons == centerButton)
        {
          clearLCD();
          on = true;
          waitForRelease();
          Iso = true;
          displayLCDCenteredString(0, "Interaction Zone");
          displayLCDCenteredString(1, "    Selected        ");
          wait1Msec(2000);
        }

        else if(nLCDButtons == rightButton)
        {
          waitForRelease();
          count = 0;
        }

        else if(nLCDButtons == leftButton)
        {
          waitForRelease();
          count--;
        }
        break;
      }//case








  }//while
  count = 0;
  while(color == false)
  {


      bLCDBacklight = true;

      switch (count){
      case 0:
        displayLCDCenteredString(0, "Blue Alliance");
        displayLCDCenteredString(1, "<     Enter     >");
        waitForPress();
        if(nLCDButtons == centerButton)
        {
          clearLCD();
          color = true;
          waitForRelease();
          red = false;

          displayLCDCenteredString(0, "Blue Alliance");
          displayLCDCenteredString(1, "   Selected      ");
          wait1Msec(2000);
        }

        else if(nLCDButtons == leftButton)
        {
          waitForRelease();
          count = 1;
        }

        else if(nLCDButtons == rightButton)
        {
          waitForRelease();
          count++;
        }
        break;



      case 1:
        displayLCDCenteredString(0, "Red Alliance");
        displayLCDCenteredString(1, "<     Enter     >");
        waitForPress();
        if(nLCDButtons == centerButton)
        {
          clearLCD();
          color = true;
          waitForRelease();
          red = true;
          displayLCDCenteredString(0, "Red Alliance");
          displayLCDCenteredString(1, "   Selected        ");
          wait1Msec(2000);
        }

        else if(nLCDButtons == rightButton)
        {
          waitForRelease();
          count = 0;
        }

        else if(nLCDButtons == leftButton)
        {
          waitForRelease();
          count--;
        }
        break;


    }//Case
  }//while

  count = 0;
  while(Program == false)
  {
    switch(count){
      case 0:
      displayLCDCenteredString(0," Autonomous 1");
      displayLCDCenteredString(1,"<    Enter     >");
      waitForPress();
      if (nLCDButtons == centerButton)
      {
        waitForRelease();
        Program = true;
        programselect = 1;
         displayLCDCenteredString(0," Autonomous 1");
         displayLCDCenteredString(1," Selected    ");
      }

      else if(nLCDButtons == rightButton)
      {
       waitForRelease();
       count++;
      }

      else if(nLCDButtons == leftButton)
      {
      waitForRelease();
      count = 10;

      }

      case 1:
        displayLCDCenteredString(0," Autonomous 2");
      displayLCDCenteredString(1,"<    Enter     >");
      waitForPress();
      if(nLCDButtons == centerButton)
      {
        waitForRelease();
        Program = true;
        programselect = 1;
         displayLCDCenteredString(0," Autonomous 2");
         displayLCDCenteredString(1," Selected    ");

      }
      else
      {
      menuTracker();
      }

        case 1:
        displayLCDCenteredString(0," Autonomous 2");
      displayLCDCenteredString(1,"<    Enter     >");
      waitForPress();
      if(nLCDButtons == centerButton)
      {
        waitForRelease();
        Program = true;
        programselect = 1;
         displayLCDCenteredString(0," Autonomous 2");
         displayLCDCenteredString(1," Selected    ");

      }
      else
      {
      menuTracker();
      }

        case 2:
        displayLCDCenteredString(0," Autonomous 2");
      displayLCDCenteredString(1,"<    Enter     >");
      waitForPress();
      if(nLCDButtons == centerButton)
      {
        waitForRelease();
        Program = true;
        programselect = 1;
         displayLCDCenteredString(0," Autonomous 2");
         displayLCDCenteredString(1," Selected    ");

      }
      else
      {
      menuTracker();
      }

        case 3:
        displayLCDCenteredString(0," Autonomous 2");
      displayLCDCenteredString(1,"<    Enter     >");
      waitForPress();
      if(nLCDButtons == centerButton)
      {
        waitForRelease();
        Program = true;
        programselect = 1;
         displayLCDCenteredString(0," Autonomous 2");
         displayLCDCenteredString(1," Selected    ");

      }
      else
      {
      menuTracker();
      }

        case 4:
        displayLCDCenteredString(0," Autonomous 2");
      displayLCDCenteredString(1,"<    Enter     >");
      waitForPress();
      if(nLCDButtons == centerButton)
      {
        waitForRelease();
        Program = true;
        programselect = 1;
         displayLCDCenteredString(0," Autonomous 2");
         displayLCDCenteredString(1," Selected    ");

      }
      else
      {
      menuTracker();
      }

        case 5:
        displayLCDCenteredString(0," Autonomous 2");
      displayLCDCenteredString(1,"<    Enter     >");
      waitForPress();
      if(nLCDButtons == centerButton)
      {
        waitForRelease();
        Program = true;
        programselect = 1;
         displayLCDCenteredString(0," Autonomous 2");
         displayLCDCenteredString(1," Selected    ");

      }
      else
      {
      menuTracker();
      }

        case 6:
        displayLCDCenteredString(0," Autonomous 2");
      displayLCDCenteredString(1,"<    Enter     >");
      waitForPress();
      if(nLCDButtons == centerButton)
      {
        waitForRelease();
        Program = true;
        programselect = 1;
         displayLCDCenteredString(0," Autonomous 2");
         displayLCDCenteredString(1," Selected    ");

      }
      else
      {
      menuTracker();
      }

        case 7:
        displayLCDCenteredString(0," Autonomous 2");
      displayLCDCenteredString(1,"<    Enter     >");
      waitForPress();
      if(nLCDButtons == centerButton)
      {
        waitForRelease();
        Program = true;
        programselect = 1;
         displayLCDCenteredString(0," Autonomous 2");
         displayLCDCenteredString(1," Selected    ");

      }
      else
      {
      menuTracker();
      }

        case 8:
        displayLCDCenteredString(0," Autonomous 2");
      displayLCDCenteredString(1,"<    Enter     >");
      waitForPress();
      if(nLCDButtons == centerButton)
      {
        waitForRelease();
        Program = true;
        programselect = 1;
         displayLCDCenteredString(0," Autonomous 2");
         displayLCDCenteredString(1," Selected    ");

      }
      else
      {
      menuTracker();
      }

        case 9:
        displayLCDCenteredString(0," Autonomous 2");
      displayLCDCenteredString(1,"<    Enter     >");
      waitForPress();
      if(nLCDButtons == centerButton)
      {
        waitForRelease();
        Program = true;
        programselect = 1;
         displayLCDCenteredString(0," Autonomous 2");
         displayLCDCenteredString(1," Selected    ");

      }
      else
      {
      menuTracker();
      }

        case 10:
        displayLCDCenteredString(0," Autonomous 2");
      displayLCDCenteredString(1,"<    Enter     >");
      waitForPress();
      if(nLCDButtons == centerButton)
      {
        waitForRelease();
        Program = true;
        programselect = 1;
         displayLCDCenteredString(0," Autonomous 2");
         displayLCDCenteredString(1," Selected    ");

      }
      else
      {
      menuTracker();
      }




    }//case


  }//3rd while



}// preauton

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

  AuonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    // This is the main execution loop for the user control program. Each time through the loop
    // your program should update motor + servo values based on feedback from the joysticks.

    // .....................................................................................
    // Insert user code here. This is where you use the joystick values to update your motors, etc.
    // .....................................................................................

    UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
  }
}
