#pragma config(Sensor, in1,    LeftLine,            sensorLineFollower)
#pragma config(Sensor, in2,    CentreLeftLine,      sensorLineFollower)
#pragma config(Sensor, in3,    CentreRightLine,     sensorLineFollower)
#pragma config(Sensor, in4,    RightLine,           sensorLineFollower)
#pragma config(Sensor, in5,    Right2Line,          sensorLineFollower)
#pragma config(Sensor, in6,    GreyCentre,          sensorLineFollower)
#pragma config(Sensor, in7,    Grey,                sensorLineFollower)
#pragma config(Sensor, in8,    Battery,             sensorReflection)
#pragma config(Sensor, in9,    Basket,              sensorDigitalOut)
#pragma config(Sensor, in10,   Sonar,               sensorSONAR, int1)
#pragma config(Sensor, in11,   LeftButton,          sensorTouch)
#pragma config(Sensor, in12,   RightButton,         sensorTouch)
#pragma config(Sensor, in13,   EncoderLeft,         sensorQuadEncoder, int3)
#pragma config(Sensor, in14,   EncoderRight,        sensorQuadEncoder, int4)
#pragma config(Sensor, in15,   LiftEncoderLeft,     sensorQuadEncoder, int5)
#pragma config(Sensor, in16,   LiftEncoderRight,    sensorQuadEncoder, int6)
#pragma config(Motor,  port1,           DriveLeft,     tmotorNormal, openLoop)
#pragma config(Motor,  port2,           DriveRight,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           LifterLeft,    tmotorNormal, openLoop)
#pragma config(Motor,  port4,           LifterLeft2,   tmotorNormal, openLoop)
#pragma config(Motor,  port5,           LifterRight,   tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port6,           LifterRight2,  tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           Tracks,        tmotorNormal, openLoop)
#pragma config(Motor,  port8,           Intake,        tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(255)

#include "Vex_Competition_Includes.c"
#include "Driving.c"
#include "Line Following.c"
#include "Lifter.c"
#include "Intake.c"
#include "Pre Autonomous.c"
//#include "Autonomous 20 Second.c"
#include "Autonomous 60 Second.c"
#include "User Control.c"
