#pragma config(Motor,  port2,           RR,     tmotorNormal, openLoop)
#pragma config(Motor,  port3,           RL,    tmotorNormal, openLoop)
#pragma config(Motor,  port4,           frontLeftMotor,      tmotorNormal, openLoop)
#pragma config(Motor,  port5,           frontRightMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "Cortex_Function_Library_v1.0.c"

task main {
  float transY;   // Y-axis translational movement
  float transX;      // X-axis translational movement (strafe)
  float rotation;  // rotation from x-axis of 2nd joystick
  float rearRight;
  float rearLeft;
  float frontLeft;
  float frontRight;

  while(true) {

    /*transY = trim(vexRT[2]);
    transX = trim(vexRT[3]);*/
    rotation = trim(vexRT[1]);  //only y-axis on rJoystick works

    if( (vexRT[Btn7U] + vexRT[Btn7D] + vexRT[Btn7L] + vexRT[Btn7R]) > 0) {
      transY = (vexRT[Btn7U] - vexRT[Btn7D]) * 50;
      transX = (vexRT[Btn7R] - vexRT[Btn7L]) * 50;
    }
    else if(vexRT[Btn6D]) {
      transY = trim(vexRT[2]);
      transX = trim(vexRT[3]);
    }

    rearRight = transY + rotation + transX;
    rearLeft = transY - rotation - transX;
    frontLeft = transY - rotation + transX;
    frontRight = -transY - rotation + transX;

    motor[RR] = -max(rearRight);
    motor[RL] = max(rearLeft);
    motor[frontLeftMotor] = max(frontLeft);
    motor[frontRightMotor] = max(frontRight);
  }
}
