#pragma config(UART_Usage, UART1, VEX_2x16_LCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, dgtl9,  LED_1,               sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Main task - flash the second LED
task main()
{
    int counter;

    // Backlight on
    bLCDBacklight = true;

    // Do our own thing
    while( true )
        {
        // toggle output
        SensorValue[ LED_1 ] = 1 - SensorValue[ LED_1 ];

        setLCDPosition(1, 0);
        displayNextLCDNumber(counter++, 0);

        wait1Msec( 250 );
        }
}
