#pragma config(Sensor, in1,    LifterPot,           sensorPotentiometer)
#pragma config(Sensor, dgtl11, LeftTouch,           sensorTouch)
#pragma config(Sensor, dgtl12, RightTouch,          sensorTouch)
#pragma config(Motor,  port1,           LeftBottomLifter, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port2,           RightUpperDrive, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           RightLowerDrive, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           LeftUpperDrive, tmotorNormal, openLoop)
#pragma config(Motor,  port5,           LeftLowerDrive, tmotorNormal, openLoop)
#pragma config(Motor,  port6,           LeftUpperLifter, tmotorNormal, openLoop)
#pragma config(Motor,  port7,           RightUpperLifter, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           LeftCollector, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port9,           RightCollector, tmotorNormal, openLoop)
#pragma config(Motor,  port10,          RightBottomLifter, tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
//#include "Michael_Function_Library_v1.0.c" //Funtion Library

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
/*
Pot values NOT CODE
arm_grounded = 1250
descore_lock_point = 1680 - 1250 = 430
low_lock_point = 2300 - arm grounded = 1050
high_lock_point = 2587 - arm_grounded = 1337

*/



void pre_auton()
{
    // All activities that occur before the competition starts
    // Example: clearing encoders, setting servo positions, ...
  time1[T1] = 0;
  SensorValue(LeftTouch) = 0;
  SensorValue(RightTouch) = 0;




  /////////////////////////////////////

  ////////////////////////////////////////



}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
task autonomous()
{
  pre_auton();
    motor[port2]=127;
    motor[port3]=127;
    wait1Msec(100);
    motor[port2]=0;
    motor[port3]=0;

  motor[port8]=127;
  motor[port9]=127;
  wait10Msec(100);
  motor[port8] = 0;
  motor[port9]=0;

  motor[port1]=-127;
  motor[port6]=-127;
  motor[port7]=-127;
  motor[port10]=-127;
  wait10Msec(100);
  motor[port1]=0;
  motor[port6]=0;
  motor[port7]=0;
  motor[port10]=0;
  //turn left (red)
    motor[port2]=127;
    motor[port3]=127;
    wait10Msec(35);
    motor[port2]=0;
    motor[port3]=0;
/*  //Turn right (blue)
    motor[port4]=127;
    motor[port5]=127;
    wait10Msec(35);
    motor[port4]=0;
    motor[port5]=0;
*/
    motor[port2] = 127;
    motor[port3]= 127;
    motor[port4]=127;
    motor[port5]= 127;
    wait10Msec(38);
    motor[port2] = 0;
    motor[port3]= 0;
    motor[port4]=0;
    motor[port5]= 0;

  motor[port1]=100;
  motor[port6]=100;
  motor[port7]=100;
  motor[port10]=100;
  wait10Msec(100);
  motor[port1]=0;
  motor[port6]=0;
  motor[port7]=0;
  motor[port10]=0;

  motor[port8] = -127;
  wait10Msec(100);
  motor[port8] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
  pre_auton();
  int goal_lock = 0;  //0 for unlocked, -1 for low gal, 1 for high goal
  //calibration for potentiometer setting the arm
  /*int low_lock_point = SensorValue[in1] + 703; //low goal potentiometer reading
                      //sets the low lock point based on the starting potentiometer point
  int high_lock_point = SensorValue[in1] + 1000; //high goal potentiometer reading*/
  //end calibrarion

	while (true)
	{
    // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................

	  //Drive Train//////////////////////////////////////////////////////////////////
                       //Right Drive
                           if(vexRT[Ch2] < 20 && vexRT[Ch2] > -20)//If input is between 20 & -20...
                               {
                                 motor[port2] = 0;                    //...drive train motors = 0
                                 motor[port3] = 0;
                               }
                               else                                   //If input is greater then 20 or smaller then -20...
                               {
                                 motor[port2] = (vexRT[Ch2]);   //...drive trian motors = scale
                                 motor[port3] = (vexRT[Ch2]);
                               }
                 //Left Drive
                           if (vexRT[Ch3] < 10 && vexRT[Ch3] > -10)//If input is between 10 & -10...
                               {
                                 motor[port4] = 0;                     //...drive train motors = 0
                                 motor[port5] = 0;
                               }
                               else                                    //If input is greater then 10 or smaller then -15...
                               {
                                 motor[port4] = (vexRT[Ch3]);    //...drive trian motors = scale
                                 motor[port5] = (vexRT[Ch3]);
                               }

         switch(vexRT[Btn6D] - vexRT[Btn6U])  //: Lifting arm conditions
          {
             case  1:motor[port1] = -127;
                     motor[port6] = -127;
                     motor[port7] = -127;
                     motor[port10] = -127;
                     break;
             case -1:motor[port1] = 127;
                     motor[port6] = 127;
                     motor[port7] = 127;
                     motor[port10] = 127;
                     break;
             case  0:motor[port1] = 0;
                     motor[port6] = 0;
                     motor[port7] = 0;
                     motor[port10]= 0;
                     break;
          }

          switch(vexRT[Btn5D] - vexRT[Btn5U])  //: Collector/plunger conditions
          {
             case  1:motor[port8] = -127;
                     motor[port9] = -127;
                     break;
             case -1:motor[port8] = 127;
                     motor[port9] = 127;
                     break;
             case  0:motor[port8] = 0;
                     motor[port9] = 0;
                     break;
          }
/*
    if(vexRT[Btn8L] == 1)//auto button close loop
      {
       goal_lock = -1;   //sets to low lock
      }
     else if(vexRT[Btn8U] == 1) {
       goal_lock = 1;    //sets to high lock
      }
     else if(vexRT[Btn8D] == 1) {
       goal_lock = 2;
      }
     else if(vexRT[Btn8R] == 1) {
       goal_lock = 2;
      }


      if(goal_lock == -1)
        lock(low_lock_point); //brings to low lock point
      else if(goal_lock == 1)
        lock(high_lock_point);//moves arm to high lock point
      ///////////////////////////////////////////////////////////////NEW STUFF TAKE THIS OUT IF IT DOESNT WORK
      else if (goal_lock == 2)
        lock(descore_low_point);//moves arm to descore lock point
      else if(goal_lock == 3)
        lock(descore_high_point);*/
  }
}
