#pragma config(Sensor, in8,    guy,                 sensorGyro)
#pragma config(Motor,  port2,           right,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           left,          tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()

{
    SensorValue[guy] = 0;
while(SensorValue[guy] < 500){

motor[right] = 127;
motor[left] = -127;
}
{
  motor[left] = 0;
  motor[right] = 0;
}
  SensorValue[guy] = 0;



   }
