task autonomous()
{
  while(SensorValue[startAuton] == 0) {

    SensorValue[solenoidL] = SensorValue[solenoidR] = 1;     //raises lift...
    wait1Msec(2000000);

}//end while statement


  motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = -127;  //drives backwards to the big goal...
  motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = -127;
  wait1Msec(900);
  killDrive();                                           // kils drivetrain...

  motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = -127;  //switches sides of the goal...
  wait1Msec(500);
  killDrive();                                           // kill drivetrain...

  setSuckSpeed(127);                                     //scores tubes in high goal...
  wait1Msec(4000);
  setSuckSpeed(0);                                       //stop collector from spinning...

  motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] =  -127;  //comes back to original side of goal...
  wait1Msec(500);
  killDrive();                                           //kill drivetrain...

  motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = 127;   //drives back to blue sqaure...
  motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = 127;
  wait1Msec(900);
  killDrive();                                           //kill drive train...

  SensorValue[solenoidL] = SensorValue[solenoidR] = 0;   //lowers lift...
  wait1Msec(3000);                                       //waits for three secs as we put 2 more preloads in...

  motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = -127;  //drives backwards to low goal...
  motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = -127;
  wait1Msec(300);
  killDrive();                                           //kil drive train...

  setSuckSpeed(127);                                     //scores tubes in low goal...
  wait1Msec(2000);
  setSuckSpeed(0);                                       //stop collector from spinning...

  motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = 127;   //comes back to blue tile...
  motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = 127;
  wait1Msec(300);

  killDrive();                                           //kill drive train.




}// task autonomous //

//////////////////////////////////////////////////////////////RED INTERACTION AUTON

/*
while(SensorValue[startAuton] == 0) {

SensorValue[liftPneu1] = SensorValue[liftPneu2] = 1;     //raises lift...
wait1Msec(2000000);

}//end while statement


motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = -127;  //drives backwards to the big goal...
motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = -127;
wait1Msec(900);
killDrive();                                           // kils drivetrain...

motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = -127;  //switches sides of the goal...
wait1Msec(500);
killDrive();                                           // kill drivetrain...

setSuckSpeed(127);                                     //scores tubes in high goal...
wait1Msec(4000);
setSuckSpeed(0);                                       //stop collector from spinning...

motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = -127;  //comes back to original side of goal...
wait1Msec(500);
killDrive();                                           //kill drivetrain...

motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = 127;   //drives back to blue sqaure...
motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = 127;
wait1Msec(900);
killDrive();                                           //kill drive train...

SensorValue[solenoidR] = SensorValue[solenoidL] = 0;   //lowers lift...
wait1Msec(3000);                                       //waits for three secs as we put 2 more preloads in...

motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = -127;  //drives backwards to low goal...
motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = -127;
wait1Msec(300);
killDrive();                                           //kil drive train...

setSuckSpeed(127);                                     //scores tubes in low goal...
wait1Msec(2000);
setSuckSpeed(0);                                       //stop collector from spinning...

motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = 127;   //comes back to blue tile...
motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = 127;
wait1Msec(300);
\
killDrive();                                           //kill drive train.




}// task autonomous //

*/
