#pragma config(UART_Usage, UART2, VEX_2x16_LCD, baudRate19200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  nick,           sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  startAuton,     sensorTouch)
#pragma config(Sensor, dgtl7,  encoderL,       sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  solenoidL,      sensorDigitalOut)
#pragma config(Sensor, dgtl10, solenoidR,      sensorDigitalOut)
#pragma config(Sensor, dgtl11, encoderR,       sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           collectorL,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port2,           frontL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frontL2,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           backL,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           backL2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           frontR,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           frontR2,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           backR,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           backR2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          collectorR,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, I2C_2, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "Zeta Function Library Worlds.c"
#include "Usercontrol Worlds.c"
#include "Zeta Autonomous Worlds.c"

//#include "LCD Worlds.c"
//#include "Variables Worlds.c"

int programselect = 1;
bool redteam = true;
bool programselecting = true;
const int totalprogramnumber = 5;

void screenrefresh()  {
  clearLCDLine(1);
  displayLCDPos(1,0);

  if (redteam == true)  {
    displayNextLCDString("RED ");
  }
  if (redteam == false)  {
    displayNextLCDString("BlUE");
  }
  displayNextLCDString("    ");
  displayNextLCDNumber(programselect);
  displayNextLCDString("     OK");
}

void pre_auton() {
  bStopTasksBetweenModes = true;

  bLCDBacklight = true;
  displayLCDPos(0,0);
  displayNextLCDString("program select");
  redteam = true;
  screenrefresh();
  time1[T1] = 0;
  while (programselecting == true)  {

    if (nLCDButtons & kButtonLeft)  {

      while (nLCDButtons & kButtonLeft)  {
      }
      if (redteam == true)  {
        redteam = false;
      }
      else if (redteam == false)  {
        redteam = true;
      }
      screenrefresh();
    }// end while
    if (nLCDButtons & kButtonCenter)  {
      while (nLCDButtons & kButtonCenter)
      {
      }
      programselect = programselect+1;
      if (programselect > totalprogramnumber)
      {
        programselect = 1;
      }
      screenrefresh();
    }
    if (nLCDButtons & kButtonRight)
    {
      clearLCDLine(0);
      clearLCDLine(1);
      displayLCDPos(0,0);
      displayNextLCDString("Robot ready");
      wait1Msec(300);
      displayNextLCDString(".");
      wait1Msec(300);
      displayNextLCDString(".");
      wait1Msec(300);
      displayNextLCDString(".");
      wait1Msec(500);
      bLCDBacklight = false;
      programselecting = false;
    }
  }
}//end pre_auton

task autonomous()
{
autonHighLow();
}//end task autonomous

task usercontrol()
{
 while (true)
	{
	drivetrain();
	collector();
	lift();
	}//end while loop
}//end task usercontrol
