#pragma config(UART_Usage, UART2, VEX_2x16_LCD, baudRate19200, IOPins, None, None)
#pragma config(Sensor, dgtl6,  startAuton,          sensorTouch)
#pragma config(Sensor, dgtl7,  encoderL,            sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  solenoidL,           sensorDigitalOut)
#pragma config(Sensor, dgtl10, solenoidR,           sensorDigitalOut)
#pragma config(Sensor, dgtl11, encoderR,            sensorQuadEncoder)
#pragma config(Motor,  port1,           collectorL,    tmotorNormal, openLoop)
#pragma config(Motor,  port2,           frontL,        tmotorNormal, openLoop)
#pragma config(Motor,  port3,           frontL2,       tmotorNormal, openLoop)
#pragma config(Motor,  port4,           backL,         tmotorNormal, openLoop)
#pragma config(Motor,  port5,           backL2,        tmotorNormal, openLoop)
#pragma config(Motor,  port6,           frontR,        tmotorNormal, openLoop)
#pragma config(Motor,  port7,           frontR2,       tmotorNormal, openLoop)
#pragma config(Motor,  port8,           backR,         tmotorNormal, openLoop)
#pragma config(Motor,  port9,           backR2,        tmotorNormal, openLoop)
#pragma config(Motor,  port10,          collectorR,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/*To example of use:
setSuckSpeed(127);
type desired speed, between -127 and 127, between ()*/
void setSuckSpeed(int speed, int duration)   {
  motor[collectorL] = motor[collectorR] = speed;
  wait1Msec(duration);
  motor[collectorL] = motor[collectorR] = 0;
}//END void

void drive_forward_msec(int speed, int duration) {
motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = speed;
  wait1Msec(duration);
motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = 0;

}//END void

void pre_auton()
{
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}//END void //


task autonomous()
{
  wait1Msec(200);
SensorValue[solenoidL] = SensorValue[solenoidR] = 1;
while(SensorValue[startAuton] == 0);

drive_forward_msec(-127,1150);


wait1Msec(1000);
setSuckSpeed(100,3500);

drive_forward_msec(127,500);

SensorValue[solenoidL] = SensorValue[solenoidR] = 0;

drive_forward_msec(127,500);

while(SensorValue[startAuton] == 0);

drive_forward_msec(-127,350);

drive_forward_msec(127,70);

setSuckSpeed(100,3000);

drive_forward_msec(127,400);

}


/*  while(SensorValue[startAuton] == 0) {

    SensorValue[solenoidL] = SensorValue[solenoidR] = 1;     //raises lift...
    wait1Msec(2000000);

}//end while statement


  motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = -127;  //drives backwards to the big goal...
  motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = -127;
  wait1Msec(900);
  killDrive();                                           // kils drivetrain...

  motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = -127;  //switches sides of the goal...
  wait1Msec(500);
  killDrive();                                           // kill drivetrain...

  setSuckSpeed(127,4000);                                     //scores tubes in high goal...
  setSuckSpeed(0,0);                                       //stop collector from spinning...

  motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] =  -127;  //comes back to original side of goal...
  wait1Msec(500);
  killDrive();                                           //kill drivetrain...

  motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = 127;   //drives back to blue sqaure...
  motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = 127;
  wait1Msec(900);
  killDrive();                                           //kill drive train...

  SensorValue[solenoidL] = SensorValue[solenoidR] = 0;   //lowers lift...
  wait1Msec(3000);                                       //waits for three secs as we put 2 more preloads in...

  motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = -127;  //drives backwards to low goal...
  motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = -127;
  wait1Msec(300);
  killDrive();                                           //kil drive train...

  setSuckSpeed(127,2000);                                     //scores tubes in low goal...
  setSuckSpeed(0,0);                                       //stop collector from spinning...

  motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = 127;   //comes back to blue tile...
  motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = 127;
  wait1Msec(300);

  killDrive();                                           //kill drive train.




}// task autonomous //
*/
//////////////////////////////////////////////////////////////RED INTERACTION AUTON

/*
while(SensorValue[startAuton] == 0) {

SensorValue[liftPneu1] = SensorValue[liftPneu2] = 1;     //raises lift...
wait1Msec(2000000);

}//end while statement


motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = -127;  //drives backwards to the big goal...
motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = -127;
wait1Msec(900);
killDrive();                                           // kils drivetrain...

motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = -127;  //switches sides of the goal...
wait1Msec(500);
killDrive();                                           // kill drivetrain...

setSuckSpeed(127);                                     //scores tubes in high goal...
wait1Msec(4000);
setSuckSpeed(0);                                       //stop collector from spinning...

motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = -127;  //comes back to original side of goal...
wait1Msec(500);
killDrive();                                           //kill drivetrain...

motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = 127;   //drives back to blue sqaure...
motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = 127;
wait1Msec(900);
killDrive();                                           //kill drive train...

SensorValue[solenoidR] = SensorValue[solenoidL] = 0;   //lowers lift...
wait1Msec(3000);                                       //waits for three secs as we put 2 more preloads in...

motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = -127;  //drives backwards to low goal...
motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = -127;
wait1Msec(300);
killDrive();                                           //kil drive train...

setSuckSpeed(127);                                     //scores tubes in low goal...
wait1Msec(2000);
setSuckSpeed(0);                                       //stop collector from spinning...

motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = 127;   //comes back to blue tile...
motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = 127;
wait1Msec(300);
\
killDrive();                                           //kill drive train.




}// task autonomous //

*/




task usercontrol()
{
	while (true)
	{

////////PNEUMATICS/////////////////////////////////////////////////////////////////////////////

 if(vexRT[Btn5U] == 1)   {      // If button 5U is pressed:
SensorValue[solenoidL] = SensorValue[solenoidR] = 1;  // ...both pneumatics shoot out.
}//end if

 else if(vexRT[Btn5D] == 1)  {   // If button 5D is pressed:
SensorValue[solenoidL] = SensorValue[solenoidR] = 0;  // ...both pneumatics shoot in.
}//end else if

//////////////////COLLECTOR///////////////////////////////////////////////////////////////////

 if(vexRT[Btn6U] == 1) {
motor[collectorL] = motor[collectorR] = 127;//if btn 6u is pressed turn both collector motors at full suck in
}//end if
 else if(vexRT[Btn6D] == 1) {
motor[collectorL] = motor[collectorR] = -127;//if btn 6d is pressed turn both collector motors at full spitout
}//end else if
 else if(vexRT[Btn8R] == 1) {
motor[collectorL] = 127;
motor[collectorR] = -127;
}//END if
 else if(vexRT[Btn8L] == 1) {
motor[collectorL] = -127;
motor[collectorR] = 127;
}//END
 else {
motor[collectorL] = motor[collectorR] = 0;//if no btn is pressed turn neither motors
}//end else



/////////////////DRIVETRAIN//////////////////////////////////////////////////////////////////

motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = vexRT[Ch3];//L drivetrain speed = y axis of L joystick values
motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = vexRT[Ch2];//R drivetrain speed = y axis of R joystick values


	}//end while loop
}//end task usercontrol
