#pragma config(Sensor, in1,    arm,                 sensorPotentiometer)
#pragma config(Sensor, in2,    leftline,            sensorLineFollower)
#pragma config(Sensor, in3,    centreline,          sensorLineFollower)
#pragma config(Sensor, in4,    rightline,           sensorLineFollower)
#pragma config(Sensor, in5,    backline,            sensorLineFollower)
#pragma config(Sensor, in10,   colour,              sensorDigitalIn)
#pragma config(Sensor, in11,   sonar,               sensorSONAR, int1)
#pragma config(Sensor, in12,   sonar2,              sensorSONAR, int2)
#pragma config(Sensor, in13,   leftsucker,          sensorRotation)
#pragma config(Sensor, in14,   rightsucker,         sensorRotation)
#pragma config(Sensor, in15,   left,                sensorQuadEncoder, int3)
#pragma config(Sensor, in16,   right,               sensorQuadEncoder, int4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Defines the platform this code will be functional for.
#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(60)
#pragma userControlDuration(0)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
//////////////////////Global Variables//////////////////////////////
//Arm position for raising arm
int armposition;
//Fast or Exact
bool exact;
bool updown = true;
////////////////////////////////////////////////////////////////////

///////////////////////////Includes/////////////////////////////////
#include "Motor Reflections.c"
#include "Subs.c"
////////////////////////////////////////////////////////////////////

//All tasks that occur before the competition starts
//Example: clearing encoders, setting motor reflectives, setting servo positions
void pre_auton()
{
//Reflect Motors
motorreflections();
}

//Autonomous code goes here
task autonomous()
{
#include "Autonomous 60 second.c"
}


task usercontrol()
{
}
