#pragma config(Sensor, dgtl9,  solenoidL,           sensorDigitalOut)
#pragma config(Sensor, dgtl10, solenoidR,           sensorDigitalOut)
#pragma config(Motor,  port1,           collectorR,    tmotorNormal, openLoop)
#pragma config(Motor,  port2,           frontR,        tmotorNormal, openLoop)
#pragma config(Motor,  port3,           frontR2,       tmotorNormal, openLoop)
#pragma config(Motor,  port4,           backR,         tmotorNormal, openLoop)
#pragma config(Motor,  port5,           backR2,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port6,           frontL,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           frontL2,       tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           backL,         tmotorNormal, openLoop)
#pragma config(Motor,  port9,           backL2,        tmotorNormal, openLoop)
#pragma config(Motor,  port10,          collectorL,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

 void setSuckSpeed(int speed) {
motor[collectorL] = motor[collectorR] = speed;
}//end void

void killDrive(){
  motor[frontR] = motor[frontR2] = motor[backR] = motor[frontL] = motor[frontL2] = motor[backL] = 0;
}


void pre_auton()  {
  /* All activities that occur before the competition starts
   Example: clearing encoders, setting servo positions, ... */
}// void //

task main()  {

/*
int X2 = 0, Y1 = 0, X1 = 0, threshold = 15; //Create "deadzone" variables. Adjust threshold value to increase/decrease deadzone
*/

while(1 == 1)  // Loop Forever
{

////////PNEUMATICS/////////////////////////////////////////////////////////////////////////////

 if(vexRT[Btn5U] == 1)   {      // If button 5U is pressed:
SensorValue[solenoidL] = SensorValue[solenoidR] = 1;  // ...both pneumatics shoot out.
}//end if

 else if(vexRT[Btn5D] == 1)  {   // If button 5D is pressed:
SensorValue[solenoidL] = SensorValue[solenoidR] = 0;  // ...both pneumatics shoot in.
}//end else if

//////////////////COLLECTOR///////////////////////////////////////////////////////////////////

 if(vexRT[Btn6U] == 1) {
motor[collectorL] = motor[collectorR] = 127;//if btn 6u is pressed turn both collector motors at full suck in
}//end if
 else if(vexRT[Btn6D] == 1) {
motor[collectorL] = motor[collectorR] = -127;//if btn 6d is pressed turn both collector motors at full spitout
}//end else if
 else {
motor[collectorL] = motor[collectorR] = 0;//if no btn is pressed turn neither motors
}//end else

motor[frontL] = motor[frontL2] = motor[backL] = motor[backL2] = vexRT[Ch3];//L drivetrain speed = y axis of L joystick values
motor[frontR] = motor[frontR2] = motor[backR] = motor[backR2] = vexRT[Ch2];//R drivetrain speed = y axis of R joystick values


}//end while loop

}//end task main
