#pragma config(UART_Usage, UART2, VEX_2x16_LCD, baudRate19200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  nick,           sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  solenoidH,      sensorDigitalOut)
#pragma config(Sensor, dgtl4,  solenoidB,      sensorDigitalOut)
#pragma config(Sensor, dgtl5,  AutonLow,       sensorTouch)
#pragma config(Sensor, dgtl6,  AutonHigh,      sensorTouch)
#pragma config(Sensor, dgtl7,  encoderL,       sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  solenoidL,      sensorDigitalOut)
#pragma config(Sensor, dgtl10, solenoidR,      sensorDigitalOut)
#pragma config(Sensor, dgtl11, encoderR,       sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           collectorL,    tmotorServoContinuousRotation, openLoop, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port2,           frontL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frontL2,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           backL,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           backL2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           frontR,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           frontR2,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           backR,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           backR2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          collectorR,    tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, I2C_2, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "Zeta Function Library Worlds.c"
#include "Usercontrol Worlds.c"
#include "Autonomous Worlds.c"

bool selecting = true;
bool skills = false;
int team = 0;         // RED = 0, BLUE = 1
int zone = 0;         // INT = 0, ISO  = 1

void pre_auton() {
  bStopTasksBetweenModes = true;

  bLCDBacklight = true;
  displayLCDPos(0,0);
  displayNextLCDString("Initializing");
  displayNextLCDChar('.');
  wait10Msec(50);
  displayNextLCDChar('.');
  wait10Msec(50);
  displayNextLCDChar('.');
  wait10Msec(50);
  wait10Msec(100);
  while(selecting == true){
    clearLCDLine(0);
    displayLCDPos(0,0);
    displayNextLCDString("RST  MATCH SKILLS");
    while(nLCDButtons != 1 && nLCDButtons != 2 && nLCDButtons != 4);
    if (nLCDButtons == 2){
      while(nLCDButtons != 0);
      clearLCDLine(0);
	    displayLCDPos(0,0);
	    displayNextLCDString("RST   RED   BLUE");
	    while(nLCDButtons != 1 && nLCDButtons != 2 && nLCDButtons != 4);
	    if (nLCDButtons == 2){
	      while(nLCDButtons != 0);
	      team = 0;
	    } else if(nLCDButtons == 4){
	      while(nLCDButtons != 0);
	      team = 1;
	    } else if(nLCDButtons == 1){
	      while(nLCDButtons != 0);
	      continue;
	    }
	    clearLCDLine(0);
	    displayLCDPos(0,0);
	    displayNextLCDString("RST   INT    ISO");
	    while(nLCDButtons != 1 && nLCDButtons != 2 && nLCDButtons != 4);
	    if (nLCDButtons == 2){
	      while(nLCDButtons != 0);
	      zone = 0;
	    } else if(nLCDButtons == 4){
	      while(nLCDButtons != 0);
	      team = 1;
	    } else if(nLCDButtons == 1){
	      while(nLCDButtons != 0);
	      continue;
	    }
    } else if(nLCDButtons == 4){
      while(nLCDButtons != 0);
      skills = true;
    } else if(nLCDButtons == 1){
      while(nLCDButtons != 0);
      continue;
    }
    selecting = false;
  }
	  if(skills == true) {
	    clearLCDLine(0);
	    displayLCDPos(0,0);
	    displayNextLCDString("    SKILLS!     ");
	    wait1Msec(2000);
	    bLCDBacklight = false;
	  } else {
	  if(team == 0 && zone == 0) {
	    clearLCDLine(0);
	    displayLCDPos(0,0);
	    displayNextLCDString("RED INTERACTION!");
	    wait1Msec(2000);
	    bLCDBacklight = false;
	  }
	  if(team == 0 && zone == 1) {
	    clearLCDLine(0);
	    displayLCDPos(0,0);
	    displayNextLCDString("RED ISOLATION!!!");
	    wait1Msec(2000);
	    bLCDBacklight = false;
	  }
	  if(team == 1 && zone == 0) {
	    clearLCDLine(0);
	    displayLCDPos(0,0);
	    displayNextLCDString("BLUE INTERACTION");
	    wait1Msec(2000);
	    bLCDBacklight = false;
	  }
	  if(team == 1 && zone == 1) {
	    clearLCDLine(0);
	    displayLCDPos(0,0);
	    displayNextLCDString("BLUE ISOLATION!!");
	    wait1Msec(2000);
	    bLCDBacklight = false;
	  }
	}
}//end pre_auton

task autonomous(){
  if(skills){
    skillsAutonomous();
  }else{
	  if(team == 0 && zone == 0){
	    redIntAutonomous();
	  }
	  if(team == 0 && zone == 1){
	    redIsoAutonomous();
	  }
	  if(team == 1 && zone == 0){
	    blueIntAutonomous();
	  }
	  if(team == 1 && zone == 1){
	    blueIsoAutonomous();
	  }
	}
}// end task autonomous

task usercontrol()
{
 while (true)
	{
	drivetrain();
	collector();
	lift();
	block();
	hoarder();
	}//end while loop
}//end task usercontrol
