#pragma config(Sensor, dgtl1,  PneuLB,              sensorDigitalOut)
#pragma config(Sensor, dgtl2,  PneuLF,              sensorDigitalOut)
#pragma config(Sensor, dgtl3,  PneuRF,              sensorDigitalOut)
#pragma config(Sensor, dgtl4,  PneuRB,              sensorDigitalOut)
#pragma config(Motor,  port1,           liftL,         tmotorNormal, openLoop)
#pragma config(Motor,  port2,           rightBack2,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           frontRight,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           backLeft,      tmotorNormal, openLoop)
#pragma config(Motor,  port6,           frontLeft,     tmotorNormal, openLoop)
#pragma config(Motor,  port7,           backLeft2,     tmotorNormal, openLoop)
#pragma config(Motor,  port10,          liftR,         tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int typeDrive = 1;
const int mecDrive = 1;
const int tracDrive = 2;
void lift(int speed)
{
  motor[liftR] = speed;
  motor[liftL] = speed;
}

task main()
{

  SensorValue[PneuLB] = SensorValue[PneuLF] = SensorValue[PneuRF] = SensorValue[PneuRB] = 0;
  while(true)
  {
    switch(typeDrive)
    {
    case mecDrive:
      {
        SensorValue[PneuLB] = SensorValue[PneuLF] = SensorValue[PneuRF] = SensorValue[PneuRB] = 0;
        motor[rightBack2] = vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
        motor[frontRight] = vexRT[Ch3] - vexRT[Ch1] - vexRT[Ch4];
        motor[backRight] =  vexRT[Ch3] - vexRT[Ch1] + vexRT[Ch4];
        motor[backLeft2] = vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
        motor[frontLeft] = vexRT[Ch3] + vexRT[Ch1] + vexRT[Ch4];
        motor[backLeft] =  vexRT[Ch3] + vexRT[Ch1] - vexRT[Ch4];
        if(vexRT[Btn8D] == 1)
          typeDrive = tracDrive;

      }//end while
      break;
    case tracDrive:
      {
        SensorValue[PneuLB] = SensorValue[PneuLF] = SensorValue[PneuRF] = SensorValue[PneuRB] = 1;
        motor[rightBack2] = motor[frontRight] = motor[backRight] = vexRT[Ch2];
        motor[backLeft2] = motor[backLeft] = motor[frontLeft] = vexRT[Ch3];
        if(vexRT[Btn8U] == 1)
          typeDrive = mecDrive;
      }
      break;
    }//switch
    lift((vexRT[Btn6D] - vexRT[Btn6U])* 127);
  }//while
}
