//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "LCDER.c"
/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  clearLCDLine(0);
    displayLCDCenteredString(0,"Which Zone?");
  while(zoner == false)
   {
     if (nLCDButtons == LeftButton)
     {
       waitForPress();
       clearLCDLine(1);
       Isolation = false;
       displayLCDPos(1,0);
      displayNextLCDString("  Interaction  >");

     }
     else if(nLCDButtons == RightButton)
     {
          waitForPress();
       clearLCDLine(1);
       Isolation = true;
       displayLCDPos(1,0);
      displayNextLCDString("<  Isolation   ");
     }
     else if (nLCDButtons == centerbutton)
     {
       zoner = true;
       clearLCDLine(1);
      waitForPress();
      if (Isolation == true)
      {
        clearLCDLine(1);
        displayLCDPos(1,0);
        displayNextLCDString("Isolation Zone");

      wait1Msec(3000);
      }
      else if (Isolation == false);
        clearLCDLine(1);
        displayLCDPos(1,0);
        displayNextLCDString("Iteraction Zone");
           wait1Msec(3000);


     }
      }


        //main code-to be placed in pre-auton section:
  bLCDBacklight = true;
  displayLCDPos(0,0);
  displayNextLCDString("program select");
  redteam = true;
  screenrefresh();
  time1[T1] = 0;
  while (programselecting == true)
  {
    if (nLCDButtons & kLeftButton)
    {
      while (nLCDButtons & kLeftButton)
      {
      }
      if (redteam == true)
      {
        redteam = false;
      }
      else if (redteam == false)
      {
        redteam = true;
      }
      screenrefresh();
    }
    if (nLCDButtons & kCenterButton)
    {
      while (nLCDButtons & kCenterButton)
      {
      }
      programselect = programselect+1;
      if (programselect > totalprogramnumber)
      {
        programselect = 1;
      }
      screenrefresh();
    }
    if (nLCDButtons & kRightButton)
    {
      clearLCDLine(0);
      clearLCDLine(1);
      displayLCDPos(0,0);
      displayNextLCDString("Robot ready");
      wait1Msec(300);
      displayNextLCDString(".");
      wait1Msec(300);
      displayNextLCDString(".");
      wait1Msec(300);
      displayNextLCDString(".");
      wait1Msec(500);
      bLCDBacklight = false;
      programselecting = false;
    }
  }
  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{

  if (Isolation == true)
  {
    if (programselect == 1);
    {
      if (redteam == true);
      {
  clearLCDLine(1);
        displayLCDPos(1,0);
        displayNextLCDString("Iteraction Zone");
           wait1Msec(3000);
         }}

  }
  else if (Isolation == false)
  {
     clearLCDLine(1);
        displayLCDPos(1,0);
        displayNextLCDString("Isolation Zone");
      }
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AuonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................

	  UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	}
}
