#pragma config(Sensor, dgtl1,  suckSensor,          sensorTouch)
#pragma config(Sensor, dgtl2,  liftUpSensor,        sensorTouch)
#pragma config(Sensor, dgtl3,  liftDownSensor,        sensorTouch)
#pragma config(Motor,  port1,           rightF,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port2,           rightUp,       tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           rightLow,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           suckR,         tmotorNormal, openLoop)
#pragma config(Motor,  port5,           suckL,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port6,           liftR,         tmotorNormal, openLoop)
#pragma config(Motor,  port7,           liftL,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           leftLow,       tmotorNormal, openLoop)
#pragma config(Motor,  port9,           leftUp,        tmotorNormal, openLoop)
#pragma config(Motor,  port10,          leftF,         tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

/*INCLUDES*/
#include "Vex_Competition_Includes.c"
#include "zeta_lib.c"

/*DEFINITIONS*/
#define FULL 127

/*PRE AUTONOMOUS*//////////////////////////////////////////////////////////////
void pre_auton() {
}

/*AUTONOMOUS*//////////////////////////////////////////////////////////////////
task autonomous() {
  drive_forward_msec(50, 300);
  suck_msec(-127, 1000);
  drive_forward_msec(-127, 310);
  wait1Msec(3000);
  drive_forward_msec(-127, 500);
  drive_forward_msec(127, 300);
  wait1Msec(3000);
  drive_forward_msec(-127, 500);
  drive_forward_msec(127, 300);

}

/*TELE OP*/////////////////////////////////////////////////////////////////////
task usercontrol() {
  while (true) {

    // drive
    setDriveLSpeed(vexRT[Ch3]);
    setDriveRSpeed(vexRT[Ch2]);

    //  suck
    setSuckLSpeed((vexRT[Btn5U] - vexRT[Btn5D])*FULL);
    setSuckRSpeed((vexRT[Btn6U] - vexRT[Btn6D])*FULL);


    //auto raise suck
    if ((vexRT[Btn8U]) == 1) {
      if (SensorValue[suckSensor] == 0) {
        setSuckSpeed(FULL);
      }
      else {
        killSuck();
      }
    }//if

    //raise lift
    setLiftSpeed((vexRT[Btn7U] - vexRT[Btn7D])*FULL);

    //auto raise lift
    if ((vexRT[Btn7L]) == 1) {
      if (SensorValue[liftUpSensor] == 0) {
        setLiftSpeed(FULL);
      }
      else {
        killLift();
      }
    }

    //auto lower lift
    if ((vexRT[Btn7R]) == 1) {
      if (SensorValue[liftDownSensor] == 0) {
        setLiftSpeed(FULL);
      }
      else {
        killLift();
      }
    }


  }//WHILE
}//TELEOP

/*END*/
