#pragma config(Sensor, in1,    detectBall,          sensorReflection)
#pragma config(Sensor, in2,    gyro,                sensorGyro)
#pragma config(Sensor, dgtl1,  btnLiftUpL,          sensorTouch)
#pragma config(Sensor, dgtl2,  btnLiftUpR,          sensorTouch)
#pragma config(Sensor, dgtl3,  btnLiftDownL,        sensorTouch)
#pragma config(Sensor, dgtl4,  btnLiftDownR,        sensorTouch)
#pragma config(Sensor, dgtl5,  btnBackL,            sensorTouch)
#pragma config(Sensor, dgtl6,  btnBackR,            sensorTouch)
#pragma config(Sensor, dgtl7,  btnFrontL,           sensorTouch)
#pragma config(Sensor, dgtl8,  btnFrontR,           sensorTouch)
#pragma config(Sensor, dgtl9,  encL,                sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encR,                sensorQuadEncoder)
#pragma config(Motor,  port2,           rightFront,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           rightMiddle,   tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           rightBack,     tmotorNormal, openLoop)
#pragma config(Motor,  port8,           suckR,         tmotorNormal, openLoop)
#pragma config(Motor,  port9,           suckL,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port1,           liftR,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port10,          liftL,         tmotorNormal, openLoop)
#pragma config(Motor,  port7,           leftBack,      tmotorNormal, openLoop)
#pragma config(Motor,  port6,           leftMiddle,    tmotorNormal, openLoop)
#pragma config(Motor,  port5,           leftFront,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

/*INCLUDES*/
#include "Vex_Competition_Includes.c"
#include "zeta_lib 2.c"
#include "zeta_auton_modes.c"

/*PRE AUTONOMOUS*//////////////////////////////////////////////////////////////
void pre_auton() {
}

/*AUTONOMOUS*//////////////////////////////////////////////////////////////////
task autonomous() {

autonHoustonOne();

}//Auton

/*TELE OP*//////////////////////////////////////////////////////////////////////
task usercontrol() {

  while (1==1) {
    tankDrive(); //Enable one  of these
    //arcadeDrive();
    suck();
    autoRaiseSuck(); //6u = up, 6d = down, 8l = rotate left, 8r = rotate right
    lift(); //5u = up, 6d = down, 7u/7l = left up/up, 7r/7d = right up/down
  }//WHILE
}//TELEOP

//////////
//*END*///
