#pragma config(Sensor, in1,    gig,                 sensorGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{


  while(SensorValue[gig] != 0)
  {
     ;
   displayLCDPos(1,0);
    displayNextLCDNumber(SensorValue[gig]);
    clearLCDLine(0);
   displayLCDPos(0,0);
  displayLCDCenteredString(0, "fatty");
  SensorValue[gig] = 50
  }

}
