#pragma config(Motor,  port2,           frontLeft,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           backLeft,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           frontRight,    tmotorNormal, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorNormal, openLoop)
#pragma config(Motor,  port6,           armLeft1,      tmotorNormal, openLoop)
#pragma config(Motor,  port7,           armLeft2,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           armRight1,     tmotorNormal, openLoop)
#pragma config(Motor,  port9,           armRight2,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AuonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  motor[frontLeft] = motor[backLeft] = vexRT[Ch3];
	  motor[frontRight] = motor[backRight] = vexRT[Ch2];

	  if(vexRT[Btn6U] != 0){
	    motor[armLeft1] = motor[armLeft2] = motor[armRight1] = motor[armRight2] = 128;
	  }
	  else if(vexRT[Btn6D] != 0){
	    motor[armLeft1] = motor[armLeft2] = motor[armRight1] = motor[armRight2] = -128;
	  }
	  else{
	    motor[armLeft1] = motor[armLeft2] = motor[armRight1] = motor[armRight2] = 0;
	  }
	}
}
