#pragma config(Sensor, in1,    Gyro,                sensorLineFollower)
#pragma config(Sensor, in2,    L1,                  sensorLineFollower)
#pragma config(Sensor, in3,    M2,                  sensorLineFollower)
#pragma config(Sensor, in4,    R3,                  sensorLineFollower)
#pragma config(Sensor, dgtl1,  encR,                sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encL,                sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  Righteye,            sensorSONAR_inch)
#pragma config(Sensor, dgtl7,  Lefteye,             sensorSONAR_inch)
#pragma config(Sensor, dgtl9,  Estop,               sensorTouch)
#pragma config(Sensor, dgtl10, Button,              sensorTouch)
#pragma config(Motor,  port2,           Right1,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           Right2,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           Right3,        tmotorNormal, openLoop)
#pragma config(Motor,  port5,           Left1,         tmotorNormal, openLoop)
#pragma config(Motor,  port6,           Left2,         tmotorNormal, openLoop)
#pragma config(Motor,  port7,           Left3,         tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include"Gyro func.c"
#include"6wheel lib.c"
task main()
