#pragma config(Motor,  port2,           RightDrive,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           LeftDrive,     tmotorNormal, openLoop)
#pragma config(Motor,  port4,           LeftArm1,     tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           RightArm,     tmotorNormal, openLoop)
#pragma config(Motor,  port6,           ArmJoint,     tmotorNormal, openLoop)
#pragma config(Motor,  port7,           LeftArm2,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           ClawMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define MAX_ARM 110
#define MAX_JOINT 100
#define MAX_CLAW 100

void tankDrive()
{
  motor[RightDrive] = vexRT[Ch2];
  motor[LeftDrive] = vexRT[Ch3];
}

void armDrive()
{
  if(vexRT[Btn5U] == 1)
  {
    motor[RightArm] = MAX_ARM;
    motor[LeftArm1] = MAX_ARM;
    motor[LeftArm2] = MAX_ARM;
  }
  else if(vexRT[Btn5D] == 1)
  {
    motor[LeftArm1] = -MAX_ARM;
    motor[LeftArm2] = -MAX_ARM;
    motor[RightArm] = -MAX_ARM;

  }
  else
  {
    motor[LeftArm1] = 0;
    motor[LeftArm2] = 0;
    motor[RightArm] = 0;
  }
}

void jointDrive()
{
  if(vexRT[Btn6U] == 1)
  {
    motor[ArmJoint] = MAX_JOINT;
  }
  else if(vexRT[Btn6D] == 1)
  {
    motor[ArmJoint] = -MAX_JOINT;
  }
  else
  {
    motor[ArmJoint] = 0;
  }
}

void clawDrive()
{
  if(vexRT[Btn8D] == 1)
  {
    motor[ClawMotor] = MAX_CLAW;
  }
  else if(vexRT[Btn8U] == 1)
  {
    motor[ClawMotor] = -MAX_CLAW;
  }
  else
  {
    motor[ClawMotor] = 0;
  }
}

task main()
{
  while (true)
  {
    tankDrive();
    armDrive();
    jointDrive();
    clawDrive();
  }
}
