#pragma config(Motor,  port1,           BackRight,     tmotorNormal, openLoop)
#pragma config(Motor,  port2,           BackLeft,      tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           FrontRight,    tmotorNormal, openLoop)
#pragma config(Motor,  port4,           FrontLeft,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////DriveTrain Variables /////////////////////////////////
int deadZone = 15;

int checkDeadZone(int val){
  if(abs(val) < deadZone){
    return 0;
  }
  else{
    return val;
  }
}

task main()
{
  while(true)
  {
    motor[port1] = checkDeadZone(vexRT[Ch2]);
    motor[port2] = checkDeadZone(vexRT[Ch3]);
    motor[port3] = checkDeadZone(vexRT[Ch2]);
    motor[port4] = checkDeadZone(vexRT[Ch3]);
  }
}
