const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
bool Iso = false;
bool on  = false;
bool red = false;
bool Program = false;
bool color = false;
bool redteam = true;
bool programselecting = true;
bool stall = false;
short Red_Program = 0;
short Blue_Program = 0;
short count = 0;
char programselect = 0;//save space
int programselect = 1;
const int totalprogramnumber = 3;
