#pragma config(Sensor, in1,    pot,                 sensorPotentiometer)
#pragma config(Sensor, dgtl2,  ncoderL,             sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  ncoderR,             sensorQuadEncoder)
#pragma config(Motor,  port6,           port6,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           port7,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           port8,         tmotorNormal, openLoop)
#pragma config(Motor,  port9,           port9,         tmotorNormal, openLoop)
#pragma config(Motor,  port10,          Claw,          tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//----------------------------------------------------------------


 task main()
{
while (true)
{
  	if(vexRT[Ch2] < 30 && vexRT[Ch2]> -30 && vexRT[Ch3] < 30 && vexRT[Ch3]> -30)
                {
                     motor[port2] = 0;
                     motor[port3] = 0;
                     motor[port4] = 0;
                     motor[port5] = 0;                 //...drive train motors = 0
                } //: if
                else
                {


                    motor[port2] =- vexRT[Ch2];//:port6
                    motor[port3] = -vexRT[Ch2];//:port7
                    motor[port4] = vexRT[Ch3];
                    motor[port5] = vexRT[Ch3];

                } //: else

                /* 	switch(vexRT[Btn5D] - vexRT[Btn5U])
                	{
                    	case  1:motor[Claw] = -127; //Close
                            	break;
                    	case -1:motor[Claw] = 127; //Open
                            	break;
                    	case  0:motor[Claw] = 0; //Do nothing
                            	break;
                            }*/
                            {
                            if(vexRT[Btn5U] == 1){
                              motor[Claw] = 127;
                            }
                            else if(vexRT[Btn5D] ==1){
                              motor[Claw] = -127;
                            }
                            else if (vexRT[Btn7D] ==1){
                              motor[Claw] = -80;
                            }
                           else{
                             motor[Claw] = 0;
                           }
                         }




      	//}
      	 /*	switch(vexRT[Btn6D] - vexRT[Btn6U]) //manual arm control
        	{
            	case  1:motor[port6] = -127;
            	motor[port7] = -127;
            	motor[port8] = -127;
            	motor[port9] = -127;

                //unlocks arm
              break;

              case -1:motor[port6] = 127;
            	motor[port7] = 127;
            	motor[port8] = 127;
            	motor[port9] = 127;
              //unlocks arm
             	break;

             	case  0: {
              motor[port6] = 0;
            	motor[port7] = 0;
            	motor[port8] = 0;
            	motor[port9] = 0;
            	break;
         	    }//switch*/
         	    if (vexRT[Btn6U] == 1 && SensorValue[dgtl6] == 1)
         	    {



         	     motor[port6] =-127;
         	    motor[port7] = -127;
         	    motor[port8] = -127;
         	    motor[port9] = - 127;
         	  }
         	   else if (vexRT[Btn6D] == 1 && SensorValue[dgtl1] == 1)
         	   {
       motor[port6] = 127;
         	    motor[port7] = 127;
         	    motor[port8] = 127;
         	    motor[port9] = 127;

         	  }






         	  else{
         	  motor[port6] = 0;
         	  motor[port7] = 0;
         	  motor[port8] = 0;
         	  motor[port9] = 0;
         	  }



              }//while
            }//task main
