#pragma config(Sensor, in2,    ppot,                sensorPotentiometer)
#pragma config(Sensor, dgtl1,  pot,                 sensorNone)
#pragma config(Sensor, dgtl3,  touchl,              sensorTouch)
#pragma config(Sensor, dgtl4,  ncoderR,             sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchh,              sensorTouch)
#pragma config(Sensor, dgtl12, TouchGoal,           sensorTouch)
#pragma config(Motor,  port2,           DriveLF,       tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           DriveRF,       tmotorNormal, openLoop)
#pragma config(Motor,  port4,           DriveRB,       tmotorNormal, openLoop)
#pragma config(Motor,  port5,           DriveLB,       tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port6,           lift1,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           lift2,         tmotorNormal, openLoop)
#pragma config(Motor,  port8,           lift3,         tmotorNormal, openLoop)
#pragma config(Motor,  port9,           lift4,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port10,          Claw,          tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(200)
/*
////////////////////////////////motor ports and explantion not code/////////////////////////////////////////////////////////
// Motor[drivetrain]                                                       \\
//backR = A<---power expander, port 4                                       \\
//backL = B,---power expander, port 5                                        \\
//frontR = port3                                                              \\
//frontL2 = port 2                                                             \\
//because my encoders were not working I had to name them dgtl...               \\
//left encoder = dgtl2 and right encoder = dgtl 4                                \\
//The Finders are just to make looking for the auton and teleop easier            \\
// In theory this program should score 20 points in auton and have a presetn teleop\\
*/
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "Lance_Function_Library_v1.0.c" //Funtion Library

/*
Pot values NOT CODE
arm_grounded = 1400 or 1250
descore_lock_point = 1748 - 1250(1400) = 347
low_lock_point = 2550 - arm grounded = 1150
descore_high_point =
high_lock_point = 2775 - arm_grounded = 1475

*/



task autonomous()
{



}// task main


//lock(low_lock_point); //<-------------------------------------pot code


//lock(low_lock_point); //<-------------------------------------pot code


//USER CONTROL/////////////////////////////////////////////////////////////////
task usercontrol()
{
 teleop();


}//taskusercontrol
