#pragma config(Sensor, in1,    pot,                 sensorPotentiometer)
#pragma config(Sensor, dgtl2,  ncoderL,             sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  ncoderR,             sensorQuadEncoder)
#pragma config(Motor,  port6,           port6,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           port7,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           port8,         tmotorNormal, openLoop)
#pragma config(Motor,  port9,           port9,         tmotorNormal, openLoop)
#pragma config(Motor,  port10,          Claw,          tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()

{







//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

{
  // 2 Second Delay

  //Clear Encoders
  SensorValue[ncoderL] = 0;
  SensorValue[ncoderR] = 0;

  motor[port10] = -127;
  wait1Msec(600);
  motor[port10] = -10;
  wait1Msec(1);

  while(SensorValue[ncoderL] > -55)  // While less than 5 rotations on the leftEncoder...
  {
    //...turn
    motor[port2] = -63;
    motor[port3] = -63;
    motor[port4] = -63;
    motor[port5] = -63;
  }
  motor[port2] = 0;
  motor[port3] = 0;
  motor[port4] = 0;
  motor[port5] = 0;

  while(SensorValue[pot] < 1475)
  {
    motor[port6] = -100;
    motor[port7] = -100;
    motor[port8] = -100;
    motor[port9] = -100;
  }
  {

    motor[port6] = -5;
    motor[port7] = -5;
    motor[port8] = -5;
    motor[port9] = -5;
  }

  SensorValue[ncoderL] = 0;
  SensorValue[ncoderR] = 0;
    while(SensorValue[ncoderL] < 220)  // While less than 5 rotations on the leftEncoder...
  {
    //...Move Forward
    motor[port2] = -63;
    motor[port3] = -63;
    motor[port4] = 63;
    motor[port5] = 63;
  }
  motor[port2] = 0;
  motor[port3] = 0;
  motor[port4] = 0;
  motor[port5] = 0;

  while(SensorValue[pot] > 937)
  {
    motor[port6] = 30;
    motor[port7] = 30;
    motor[port8] = 30;
    motor[port9] = 30;
  }


    motor[port6] = 0;
    motor[port7] = 0;
    motor[port8] = 0;
    motor[port9] = 0;


      motor[port10] = -127;
  wait1Msec(600);
 motor[port10] = 0;
 wait1Msec(1);
     while(SensorValue[ncoderL] > -215)  // While less than 5 rotations on the leftEncoder...
  {
    //...Move back
    motor[port2] = 63;
    motor[port3] = 63;
    motor[port4] = -63;
    motor[port5] = -63;
  }
  motor[port2] = 0;
  motor[port3] = 0;
  motor[port4] = 0;
  motor[port5] = 0;





}// task main


  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

//	AuonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{


//----------------------------------------------------------------




  	if(vexRT[Ch2] < 30 && vexRT[Ch2]> -30 && vexRT[Ch3] < 30 && vexRT[Ch3]> -30)
                {
                     motor[port2] = 0;
                     motor[port3] = 0;
                     motor[port4] = 0;
                     motor[port5] = 0;                 //...drive train motors = 0
                } //: if
                else
                {


                    motor[port2] =- vexRT[Ch2];//:port6
                    motor[port3] = -vexRT[Ch2];//:port7
                    motor[port4] = vexRT[Ch3];
                    motor[port5] = vexRT[Ch3];

                } //: else

                /* 	switch(vexRT[Btn5D] - vexRT[Btn5U])
                	{
                    	case  1:motor[Claw] = -127; //Close
                            	break;
                    	case -1:motor[Claw] = 127; //Open
                            	break;
                    	case  0:motor[Claw] = 0; //Do nothing
                            	break;
                            }*/
                            {
                            if(vexRT[Btn5U] == 1){
                              motor[Claw] = 127;
                            }
                            else if(vexRT[Btn5D] ==1){
                              motor[Claw] = -127;
                            }
                            else if (vexRT[Btn7D] ==1){
                              motor[Claw] = -80;
                            }
                           else{
                             motor[Claw] = 0;
                           }
                         }




      	//}
      	 /*	switch(vexRT[Btn6D] - vexRT[Btn6U]) //manual arm control
        	{
            	case  1:motor[port6] = -127;
            	motor[port7] = -127;
            	motor[port8] = -127;
            	motor[port9] = -127;

                //unlocks arm
              break;

              case -1:motor[port6] = 127;
            	motor[port7] = 127;
            	motor[port8] = 127;
            	motor[port9] = 127;
              //unlocks arm
             	break;

             	case  0: {
              motor[port6] = 0;
            	motor[port7] = 0;
            	motor[port8] = 0;
            	motor[port9] = 0;
            	break;
         	    }//switch*/
         	    if (vexRT[Btn6U] == 1 && SensorValue[dgtl6] == 1)
         	    {



         	     motor[port6] =-127;
         	    motor[port7] = -127;
         	    motor[port8] = -127;
         	    motor[port9] = - 127;
         	  }
         	   else if (vexRT[Btn6D] == 1 && SensorValue[dgtl1] == 1)
         	   {
       motor[port6] = 127;
         	    motor[port7] = 127;
         	    motor[port8] = 127;
         	    motor[port9] = 127;

         	  }






         	  else{
         	  motor[port6] = 0;
         	  motor[port7] = 0;
         	  motor[port8] = 0;
         	  motor[port9] = 0;
         	  }



              }//while
            }//task main

	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................

	  //UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
