#pragma config(Sensor, in1,    RightLine,           sensorLineFollower)
#pragma config(Sensor, in2,    MidLine,             sensorLineFollower)
#pragma config(Sensor, in3,    LeftLine,            sensorLineFollower)
#pragma config(Sensor, dgtl1,  EncoderR,            sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  EncoderL,            sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  Frontsonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           LeftLift1,     tmotorNormal, openLoop)
#pragma config(Motor,  port2,           DriveL,        tmotorNormal, openLoop)
#pragma config(Motor,  port3,           DriveL2,       tmotorNormal, openLoop)
#pragma config(Motor,  port4,           DriveR,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           DriveR2,       tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port6,           Gate1,         tmotorNormal, openLoop)
#pragma config(Motor,  port7,           Gate2,         tmotorNormal, openLoop)
#pragma config(Motor,  port10,          LeftLift2,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "Cortex_awesome.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{

  bLCDBacklight = true;
  displayLCDPos(0,0);
  displayNextLCDString("program select");
  redteam = true;
  screenrefresh();
  time1[T1] = 0;
  while (programselecting == true)
  {
    if (nLCDButtons & kLeftButton)
    {
      while (nLCDButtons & kLeftButton)
      {
      }
      if (redteam == true)
      {
        redteam = false;
      }
      else if (redteam == false)
      {
        redteam = true;
      }
      screenrefresh();
    }
    if (nLCDButtons & kCenterButton)
    {
      while (nLCDButtons & kCenterButton)
      {
      }
      programselect = programselect+1;
      if (programselect > totalprogramnumber)
      {
        programselect = 1;
      }
      screenrefresh();
    }
    if (nLCDButtons & kRightButton)
    {
      clearLCDLine(0);
      clearLCDLine(1);
      displayLCDPos(0,0);
      displayNextLCDString("Robot ready");
      wait1Msec(300);
      displayNextLCDString(".");
      wait1Msec(300);
      displayNextLCDString(".");
      wait1Msec(300);
      displayNextLCDString(".");
      wait1Msec(500);
      bLCDBacklight = false;
      programselecting = false;
    }
  }
  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  if (programselect == 1);
  {
    if(redteam == true);
    {

         foward_until();
         drive_straight(127,100);
        TurnEnc(127,350);
          linesonar(63,5, 10);// follows line until the sonar sees something 5 inches away.
         //Line_straight(100,550.20);
     straight(-127, 250);



}

}


if (programselect == 2);
{
  if (redteam == true);
  {
    Line_straight(63,350);
     Stop();
  }

}
}


  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

 // Remove this function call once you have "real" code.


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

	  motor[port2] = vexRT[Ch2];
	  motor[port3] = vexRT[Ch2];
	  motor[port4] = vexRT[Ch3];
	  motor[port5] = vexRT[Ch3];
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................


	}
}
