#pragma config(Motor,  port2,           Leftmotor,      tmotorNormal, openLoop)
#pragma config(Motor,  port3,           Rightmotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port4,           Frontmotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port5,           Backmotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void Stop()//Func. to make the motors stop...
{
    motor[Leftmotor] = 0;
    motor[Rightmotor] = 0;
    motor[Frontmotor] = 0;
    motor[Backmotor] = 0;
}


  task main()
{


while(true){
motor[Backmotor] = vexRT[Ch4];//Asigning motors.
motor[Frontmotor] = vexRT[Ch4];
motor[Rightmotor] = vexRT[Ch3];
motor[Leftmotor] = vexRT[Ch3];


}//task main
