#pragma config(Sensor, in1,    LeftLine,            sensorLineFollower)
#pragma config(Sensor, in2,    CentreLeftLine,      sensorLineFollower)
#pragma config(Sensor, in3,    CentreRightLine,     sensorLineFollower)
#pragma config(Sensor, in4,    RightLine,           sensorLineFollower)
#pragma config(Sensor, in5,    Right2Line,          sensorLineFollower)
#pragma config(Sensor, in6,    GreyCentre,          sensorLineFollower)
#pragma config(Sensor, in7,    Grey,                sensorLineFollower)
#pragma config(Sensor, in8,    Pot_Arm,             sensorPotentiometer)
#pragma config(Sensor, dgtl1,  EncoderR,            sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  EncoderL,            sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  TouchRight,          sensorTouch)
#pragma config(Sensor, dgtl6,  TouchLeft,           sensorTouch)
#pragma config(Sensor, dgtl7,  Arm_limit,           sensorTouch)
#pragma config(Sensor, dgtl8,  Arm_closed,          sensorTouch)
#pragma config(Motor,  port1,           SuckerR,       tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port2,           DriveR1,       tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           DriveR2,       tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           DriveL1,       tmotorNormal, openLoop)
#pragma config(Motor,  port5,           DriveL2,       tmotorNormal, openLoop)
#pragma config(Motor,  port6,           ArmLD,         tmotorNormal, openLoop)
#pragma config(Motor,  port7,           ArmLU,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           ArmRD,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port9,           ArmRU,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port10,          SuckerL,       tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Delta_Function_Library_1.0.c"

int arm_grounded;
int low_lock_point;
int high_lock_point;
int pre_auton_complete = 0;

void pre_auton()
{
  SensorValue[EncoderL] = 0;
  SensorValue[EncoderR] = 0;
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
  arm_grounded = SensorValue[Pot_Arm];
  low_lock_point = arm_grounded + 800; //low goal potentiometer reading
                      //sets the low lock point based on the starting potentiometer point
  high_lock_point = arm_grounded + 1100; //high goal potentiometer reading
  arm_grounded += 100;
  pre_auton_complete = 1;
}
