#pragma config(ProgramType, StandaloneUSBCable)
    #pragma config(Sensor, in1,    pot,                 sensorPotentiometer)
#pragma config(Sensor, dgtl1,  limit,               sensorNone)
#pragma config(Sensor, dgtl2,  ncoderL,             sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  ncoderR,             sensorQuadEncoder)
#pragma config(Motor,  port6,           port6,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           port7,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           port8,         tmotorNormal, openLoop)
#pragma config(Motor,  port9,           port9,         tmotorNormal, openLoop)
#pragma config(Motor,  port10,          Claw,          tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                     - Program Chooser (live) -                                     *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program takes the content of "Program Chooser.c" and uses it in a separate task running      *|
|*  alongside your own code.  If you apply this template to all of your programs, you can run         *|
|*  programs "on the fly" or in succession without having to power cycle.                             *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  LCD connected to both RX and TX of UART 2.                                                  *|
|*    2)  Enable the file system (Robot > Compile and Download ... > Optional File System)            *|
|*    3)  Set "Program Chooser.c" as the default, and all other programs (including this one)         *|
|*        should be compiled to the File System.                                                      *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    UART Port 2         none                VEX LCD Screen        Be sure to use both RX and TX.    *|
\*-----------------------------------------------------------------------------------------------4246-*/


//============================================| My Code |=============================================
task MyCode()
{
  while(true)
  {


//----------------------------------------------------------------



{
while (true)
{
  	if(vexRT[Ch2] < 30 && vexRT[Ch2]> -30 && vexRT[Ch3] < 30 && vexRT[Ch3]> -30)
                {
                     motor[port2] = 0;
                     motor[port3] = 0;
                     motor[port4] = 0;
                     motor[port5] = 0;                 //...drive train motors = 0
                } //: if
                else
                {


                    motor[port2] = -vexRT[Ch2];//:port6
                    motor[port3] = -vexRT[Ch2];//:port7
                    motor[port4] = vexRT[Ch3];
                    motor[port5] = vexRT[Ch3];

                } //: else

                 	switch(vexRT[Btn5U] - vexRT[Btn5D])
                	{
                    	case  1:motor[Claw] = -127; //Close
                            	break;
                    	case -1:motor[Claw] = 127; //Open
                            	break;
                    	case  0:motor[Claw] = 0; //Do nothing
                            	break;
      	}
      	 	/*switch(vexRT[Btn6D] - vexRT[Btn6U]) //manual arm control
        	{
            	case  1:motor[port6] = -127;
            	motor[port7] = -127;
            	motor[port8] = -127;
            	motor[port9] = -127;

                //unlocks arm
              break;

              case -1:motor[port6] = 127;
            	motor[port7] = 127;
            	motor[port8] = 127;
            	motor[port9] = 127;
              //unlocks arm
             	break;

             	case  0: {
              motor[port6] = 0;
            	motor[port7] = 0;
            	motor[port8] = 0;
            	motor[port9] = 0;
            	break;
         	    }//switch*/
         	    if (vexRT[Btn6U] == 1){
         	    motor[port6] = 127;
         	    motor[port7] = 127;
         	    motor[port8] = 127;
         	    motor[port9] = 127;
         	  }
         	   else if (vexRT[Btn6D] == 1 && SensorValue[dgtl1] == 1)
         	   {
         	    motor[port6] = -127;
         	    motor[port7] = -127;
         	    motor[port8] = -127;
         	    motor[port9] =  -127;
         	  }

         	  else{
         	  motor[port6] = 0;
         	  motor[port7] = 0;
         	  motor[port8] = 0;
         	  motor[port9] = 0;
         	  }



              }//while
            }//task main
    //-----------------------------------

      // Put your code here.

    //-----------------------------------

    wait10Msec(20); // Leave the wait statement at the end of this while loop to help the multitasking process.
  }
}
//====================================================================================================

















int nCurrentFileIndex;

//---------------------------------------| Select Next Program |--------------------------------------
bool bSelectNextProgram(int nDirection)
{
  //
  // Increment (or decrement) to the next valid file slot. Skip over empty file slots.
  //
  int nAttempts = 0;

  for (nAttempts = 0; nAttempts < kNumbOfFile; ++nAttempts)
  {
    nCurrentFileIndex += nDirection;
    if (nCurrentFileIndex < 1)
      nCurrentFileIndex = kNumbOfFiles - 1;
    if (nCurrentFileIndex >= kNumbOfFiles)
      nCurrentFileIndex = 1;
    if (bValidFile(nCurrentFileIndex))
      return true;
  }
  return false;
}
//----------------------------------------------------------------------------------------------------

//============================================| Chooser |=============================================
task Chooser()
{
  nCurrentFileIndex = 0;
  bLCDBacklight = true;
	PlaySound(soundFastUpwardTones);
  if (!bSelectNextProgram(+1))
	{
		// File system is empty

	  displayLCDCenteredString(1, "No programs");
		while (true)
		{
		  PlaySound(soundBlip);
		  wait1Msec(500);
	  }
	}
	displayLCDCenteredString(1, "Select A Pgm");
	wait1Msec(1000);

	while (true)
  {
    if (nLCDButtons & kLeftButton)
    {
      bSelectNextProgram(-1);
      while (nLCDButtons != kNoButtons)
      {}
    }

    else if (nLCDButtons & kRightButton)
    {
      bSelectNextProgram(+1);
      while (nLCDButtons != kNoButtons)
      {}
    }

    else if (nLCDButtons & kRightButton)
    {
      bSelectNextProgram(+1);
    }


    else if (nLCDButtons & kCenterButton)
    {
      // Start execution of current selection

      while (nLCDButtons != kNoButtons)
      {}
      setProgramNumber(nCurrentFileIndex);
    }

    // Display current selection on LCD

    displayFileName(0, nCurrentFileIndex);
    displayLCDPos(1, 0);
    displayNextLCDString("\F7     Run      \F6");// F6 and F7 are left, right arrows

    wait10Msec(20);
  }
  return;
}
//====================================================================================================


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  StartTask(Chooser);   // Start the 'Chooser' Task

  StartTask(MyCode);    // Start the 'MyCode' Task (user's code)

  while(true)           // Infinite loop to keep your program alive
  {
    wait1Msec(20);      // A short wait to help the multitasking process.
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
