 #pragma config(Sensor, in1,    pot,                 sensorPotentiometer)
#pragma config(Sensor, dgtl2,  ncoderR,             sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  ncoderL,             sensorQuadEncoder)
#pragma config(Motor,  port6,           port6,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port7,           port7,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port8,           port8,         tmotorNormal, openLoop)
#pragma config(Motor,  port9,           port9,         tmotorNormal, openLoop)
#pragma config(Motor,  port10,          Claw,          tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//






//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  // 2 Second Delay

  //Clear Encoders
  SensorValue[ncoderL] = 0;
  SensorValue[ncoderR] = 0;

  motor[port10] = -127;
  wait1Msec(600);
  motor[port10] = -10;
  wait1Msec(1);

  while(SensorValue[ncoderL] < 35)  // While less than 5 rotations on the leftEncoder...
  {
    //...turn
    motor[port2] = -63;
    motor[port3] = -63;
    motor[port4] = -63;
    motor[port5] = -63;
  }
  motor[port2] = 0;
  motor[port3] = 0;
  motor[port4] = 0;
  motor[port5] = 0;

  while(SensorValue[pot] < 1475)
  {
    motor[port6] = -100;
    motor[port7] = -100;
    motor[port8] = -100;
    motor[port9] = -100;
  }
  {

    motor[port6] = -5;
    motor[port7] = -5;
    motor[port8] = -5;
    motor[port9] = -5;
  }

  SensorValue[ncoderL] = 0;
  SensorValue[ncoderR] = 0;
    while(SensorValue[ncoderL] < 220)  // While less than 5 rotations on the leftEncoder...
  {
    //...Move Forward
    motor[port2] = -63;
    motor[port3] = -63;
    motor[port4] = 63;
    motor[port5] = 63;
  }
  motor[port2] = 0;
  motor[port3] = 0;
  motor[port4] = 0;
  motor[port5] = 0;

  while(SensorValue[pot] > 937)
  {
    motor[port6] = 30;
    motor[port7] = 30;
    motor[port8] = 30;
    motor[port9] = 30;
  }


    motor[port6] = 0;
    motor[port7] = 0;
    motor[port8] = 0;
    motor[port9] = 0;


      motor[port10] = -127;
  wait1Msec(600);
 motor[port10] = 0;
 wait1Msec(1);
     while(SensorValue[ncoderL] > -215)  // While less than 5 rotations on the leftEncoder...
  {
    //...Move back
    motor[port2] = 63;
    motor[port3] = 63;
    motor[port4] = -63;
    motor[port5] = -63;
  }
  motor[port2] = 0;
  motor[port3] = 0;
  motor[port4] = 0;
  motor[port5] = 0;





}// task main
