#pragma config(Sensor, in1,    pot,                 sensorPotentiometer)
#pragma config(Sensor, dgtl1,  ncoder1,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ncoder2,             sensorQuadEncoder)
#pragma config(Sensor, dgtl12, TouchGoal,           sensorTouch)
#pragma config(Motor,  port2,           DriveR,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           DriveL,        tmotorNormal, openLoop)
#pragma config(Motor,  port4,           Lift1,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           Lift2,         tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port6,           Lift3,         tmotorNormal, openLoop)
#pragma config(Motor,  port7,           Lift4,         tmotorNormal, openLoop)
#pragma config(Motor,  port8,           Claw,          tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//






task main()
{
  wait1Msec(2000);  // 2 Second Delay
motor[DriveL] = -100;
motor[DriveR] = -100;
wait1Msec(2000);

motor[port2] = 0;
motor[port3] = 0;
wait1Msec(250);

motor[DriveL] = 100;
motor[DriveR] = -100;
wait1Msec(1000);

motor[DriveL] = 100;
motor[DriveR] = 100;

wait1Msec(250);
motor[Claw] = 127;
wait1Msec(500);

motor[DriveL] = -100;
motor[DriveR] = 100;
wait1Msec(1000);




}





//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
