#pragma config(Sensor, in1,    L1,                  sensorLineFollower)
#pragma config(Sensor, in2,    M2,                  sensorLineFollower)
#pragma config(Sensor, in3,    R3,                  sensorLineFollower)
#pragma config(Sensor, dgtl1,  encR,                sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encL,                sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  Righteye,            sensorSONAR_inch)
#pragma config(Sensor, dgtl7,  Lefteye,             sensorSONAR_inch)
#pragma config(Sensor, dgtl9,  Estop,               sensorTouch)
#pragma config(Sensor, dgtl10, Button,              sensorTouch)
#pragma config(Motor,  port2,           Right1,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           Right2,        tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           Right3,        tmotorNormal, openLoop)
#pragma config(Motor,  port5,           Left1,         tmotorNormal, openLoop)
#pragma config(Motor,  port6,           Left2,         tmotorNormal, openLoop)
#pragma config(Motor,  port7,           Left3,         tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "6wheel lib.c"
#pragma platform(VEX)
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  clearenc();
  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
task e_stop()
{
  while(true)
  {
    if(SensorValue(Estop) == 1)
    {
      StopAllTasks(); // this ends the program
    }
    wait1Msec(10);  // this prevents the current task from hogging the CPU
  }
}





task autonomous()
{
  StartTask(e_stop);




  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////



task usercontrol()
{
  // User ontrol code here, inside the loop
  StartTask(e_stop);
while(true){
  {
    motor[Right1] = vexRT[Ch2];
    motor[Right2] = vexRT[Ch2];
    motor[Right3] =  vexRT[Ch2];
    motor[Left1] = vexRT[Ch3];
    motor[Left2] =  vexRT[Ch3];
    motor[Left3] =  vexRT[Ch3];
  }
}


}//while
